services:
  # Combined Service (Frontend + Backend on same port)
  - type: web
    name: resumebot
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: AI_PROVIDER
        value: gemini
      - key: NEXT_PUBLIC_API_URL
        value: https://resumebot-4599.onrender.com
      - key: NEXT_PUBLIC_APP_URL
        value: https://resumebot-4599.onrender.com
